import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Slider from "@/components/Slider";
import AllProducts from "@/components/AllProducts";
import Slider2 from "@/components/Slider2";
import RoundedPhoto from "@/components/RoundedPhoto";
import Blog from "@/components/Blog";
// import {data} from '../pages/api/hello';

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex flex-col">
          <Slider data={data} />
          <Slider2 data={data}/>
          <AllProducts data={data}/>
          <RoundedPhoto data={data}/>
          <Blog/>
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch("https://fakestoreapi.com/products");
  const data = await res.json();
  console.log(data);
  return { props: { data } };
};
